version: '3.3'
services:

  # Rails App
  app:
    build: .
    command: bundle exec puma -C config/puma.rb
    volumes:
      - ./:/var/www/app
    depends_on:
      - db
    expose:
      - "3000"
    ports:
      - "3000:3000"

  # Database
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - udemy-data:/var/lib/postgresql/data

  # Database UI
  pgweb:
    container_name: pgweb
    restart: always
    image: sosedoff/pgweb
    ports:
      - "8082:8081"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/udemy_development?sslmode=disable
    depends_on:
      - db

volumes:
  udemy-data:
