default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: postgres
  pool: 5

development:
  <<: *default
  database: udemy_development

test:
  <<: *default
  database: udemy_test

production:
  <<: *default
  database: udemy_test
